kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: default           #HDD disk
  #storageClassName: managed-premium  #SSD disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi