apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq-management-app
spec:
  ports:
    - port: xxxx
  selector:
    app: rabbitmq-management-app
    tier: frontend
  type: LoadBalancer
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq-management-app
spec:
  selector:
    matchLabels:
      app: rabbitmq-management-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-management-app
        tier: frontend
    spec:
      containers:
      - image: rabbitmq-management-app
        name: rabbitmq
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: SWQOKODSQALRPCLNMEQG
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
